version: 2

container: &container
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
    - image: circleci/mongo:latest
    - image: cypress/base:latest
      environment:
        TERM: xterm

jobs:
  prepare:
    <<: *container
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: sudo yarn global add mongo-seeding-cli

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install
      
      - run:
          name: Build app
          command: yarn build

      - run:
          name: Seed data
          command: yarn seed

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *container
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Start app
          command: yarn start
          background: true

      - run:
          name: Run cypress test
          command: yarn test:wait

workflows:
  version: 2
  build-and-test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
