version: 2

container: &container
  working_directory: ~/app
  docker:
    - image: cypress/base:latest
      environment:
        TERM: xterm
    - image: circleci/mongo:latest
      environment:
        MONGO_URL: "mongodb://localhost:27017/envision"

jobs:
  prepare:
    <<: *container
    steps:
      - checkout
      - run: yarn global add mongo-seeding-cli

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      # - run:
      #     name: Wait for Mongo
      #     command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s
      
      - run:
          name: Build app
          command: yarn build

      - run:
          name: Seed data
          command: yarn seed

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *container
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Start app
          command: yarn start
          background: true
      
      - run:
          command: yarn cypress:install

      - run:
          name: Run cypress test
          command: yarn test:wait

workflows:
  version: 2
  build-and-test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
